ru:
  hello: "Привет. Мое имя Ревока. Я могу помочь тебе выучить новый язык. Но я не чат-бот!\nВведи /help чтобы узнать о командах."
  fail: 'Что-то пошло не так. Попробуй снова.'
  help:
    idle: "Мое имя Ревока. Я могу помочь тебе выучить новый язык.\n
    Если у тебя еще нет словаря, тебе стоит создать новый с помощью команды /new_vocabulary . Новый словарь автоматически станет активным, но если ты хочешь вернуться к другим словарям, набери /switch_vocabulary.\n
    Пустые словари невроятно скучные: добавь слово в словарь с помощью команды /add_word.\n
    Если ты не знаешь перевода, лучше всего набрать команду /translate_word и затем добавить слово в словарь.
    Для того, чтобы потренироваться, набери /random_word или /random_translation , чтобы получить случайное слово из словаря для перевода.\n
    Список всех слов словаря доступен по команде /list_words.\n
    Чтобы удалить словарь, используй команду /delete_vocabulary.\n
    Для изменения частоты оповещений воспользуйся командой /change_notification_settings и следуй инструкциям.\n
    Ты так же можешь поменять мойосновной язык командой /change_language.
    Надеюсь, тебе понравится работать со мной. Но давай не будем болтать по мелочам."
    new: "Создаешь новый словарь? Выбери язык, который хочешь изучить, потом язык, который знаешь. Вот и все.\n
    Для отмены воспользуйся командой /cancel"
    add: "Добавляешь слово в словарь? Сначала добавь само слово, затем его переводы.\n
    Для отмены воспользуйся командой /cancel"
    switch: "Хочешь поменять словарь? Выбери нужный из списка.\n
    Для отмены воспользуйся командой /cancel"
    delete:  "Хочешь удалить словарь? Выбери нужный из списка.\n
    Для отмены воспользуйся командой /cancel"
    random:
      word: "Мы играем в слова. Я тебе слово, ты мне перевод. Смекаешь?\n
    Для отмены воспользуйся командой /cancel"
      translation: "Мы играем в слова. Я тебе перевод слова, а ты мне само слово. Смекаешь?\n
    Для отмены воспользуйся командой /cancel"
    notifications: "Хочешь сменить частоту оповещений? Следуй инструкциям и все получится.\n
    Для отмены воспользуйся командой /cancel"
    language_change: "Хочешь поменять язык общения? Сейчас доступно лишь четыре: Английский, Русский, Испанский и Французский.\n
    Для отмены воспользуйся командой /cancel"
    unknown: "Честно говоря, я не знаю, что ты делаешь сейчас."
  new_vocabulary: 
    learn: 'Выбери язык, который хочешь изучить:'
    know: 'Выбери язык, который знаешь:'
    wrong: 'Пожалуйста, используй кнопки или набери правильный язык.'
    identical: "Тут нечего учить: языки ничем не отличаются. Выбери другие."
    already_have: "У тебя уже есть такой словарь. Зачем тебе еще один?"
    created: "Ты создал %{llang}-%{klang} словарь. Добавь скорее слова - тут очень пусто!"
  switch_vocabulary: 
    intro: 'Выбери нужный словарь:'
    one: 'Я не могу этого сделать, потому что у тебя всего один словарь.'
    none: 'Эм... У тебя нет ни одного словаря. Лучше создай новый, пока я не разозлилась.'
    error: "У тебя нет такого словаря.\nПожалуйста, используй кнопки или введи правильное название."
    success: 'Я успешно поменяла активный словарь.'
  delete_vocabulary: 
    intro: 'Выбери нужный словарь:'
    one: "Я не могу этого сделать, потому что у тебя всего один словарь. Его нельзя удалить."
    none: 'Эм... У тебя нет ни одного словаря. Лучше создай новый, пока я не разозлилась.'
    error: "У тебя нет такого словаря.\nПожалуйста, используй кнопки или введи правильное название."
    success: 'Я успешно удалила словарь.'
  add:
    word: 'Введи слово: '
    translation: "Хорошо, а теперь его перевод.\nКстати, возможный перевод: %{possible_translation}"
    more:
      question: 'Круто, хочешь ввести еще несколько переводов?'
      positive: 'Окей.'
      negative: 'Слово %{word} было добавлено в словарь.'
  random:
    none: "У тебя нет слов в словаре. Добавь их сначала."
    translate: 'Переведи на %{lang}: %{word}'
    good: "Правильно!"
    bad: 'Неверно. Продолжай тренироваться'
  not_implemented: "К сожалению, я пока не умею это. Потерпи немного."
  list: "%{num} слов в твоем %{llang}-%{klang} словаре:\n%{words}"
  translate:
    question: "Введи слово для перевода:"
  notification:
    intro: 'Сначала выбери как часто ты хочешь получать мои оповещения:'
    no_vocabulary: "Ты не можешь получать оповещения, пока у тебя нет словаря!"
    none: 'Ты не будешь получать оповещения.'
    selected_period: 'Теперь, через сколько %{period}s ты хочешь получать мои оповещения?'
    success: "Настройки были изменены."
    error: "Что-то пошло не так. Помни, ты должен ввести число, не меньше 1 и не больше 30. Попробуй снова."
  change_language: 
    question: 'Выбери язык общения:'
    success: 'Язык общения изменен.'
    error: 'Пожалуйста, используй кнопки или введи правильное название.'
  not_a_comand: "Это не команда. Я не понимаю тебя. Я могу помочь в изучении новых языков, но я не чат-бот, глупый!"